"""
UI Package

Exports a variety of classes that together comprise the user interface, they are listed below:

AnalysisDialog.py: Dialog for performing tracking analysis and video playback
MainWindow.py: Main windows of the application, central point of operation from a user perspective
RunningExperimentDialog.py: A minor dialog to indicate progress of running experiments
SettingsDialog.py: Dialog for setup configuration and live camera view

All other files are generated by QtDesigner, altering these directly may result in the application crashing. It is
strongly recommended that any altering to layout or design be performed in QtDesigner.
"""