# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  issues:
    types : [ opened ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  createCard:
      runs-on: ubuntu-latest
      steps:
        - name: Create or Update Project Card
          uses: peter-evans/create-or-update-project-card@v1.1.4
          with:
            project-name: CI-VTS Project
            column-name: To do
