name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  issues:
    types : [ opened ]
    
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  createCard:
      runs-on: ubuntu-latest
      steps:
      - name: Create or Update Project Card
        uses: peter-evans/create-or-update-project-card@v1.1.4
        with:
          # The number of the project. Semi-required. Either `project-number` OR `project-name` must be supplied.
          project-number: 1
          
          # The name of the project. Semi-required. Either `project-number` OR `project-name` must be supplied. Note that a project's name is not unique. The action will use the first matching project found.
          project-name: CI-VTS Project
          # The name of the column to add a card to, or move an existing card to.
          column-name: To do
